"""Generate a deterministic gallery of the five held-out composed sensor shifts."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from irforge_sim.config import CONFIRMATORY_FAMILIES
from irforge_sim.image_formation import generate_sample


ROOT = Path(__file__).resolve().parents[1]


def target_sample(family: str):
    for seed in range(1000, 1080):
        sample = generate_sample(seed, family)
        if sample.has_target:
            return sample
    raise RuntimeError(f"no target sample found for {family}")


def main() -> None:
    plt.rcParams.update({"font.family": "serif", "font.serif": ["Times New Roman", "DejaVu Serif"], "font.size": 8, "savefig.dpi": 300})
    fig, axes = plt.subplots(1, 5, figsize=(6.75, 1.75))
    labels = {
        "blur_noise": "Blur + noise",
        "attenuation_contrast": "Attenuation + contrast",
        "badpixel_fpn": "Bad pixels + FPN",
        "clutter_blur": "Clutter + blur",
        "triple_shift": "Triple shift",
    }
    for ax, family in zip(axes, CONFIRMATORY_FAMILIES, strict=True):
        sample = target_sample(family)
        low, high = np.percentile(sample.image, [1, 99])
        ax.imshow(sample.image, cmap="magma", vmin=low, vmax=high, interpolation="nearest")
        if sample.target_xy:
            x, y = sample.target_xy
            ax.scatter([x], [y], s=90, facecolors="none", edgecolors="#56E4C1", linewidths=1.1)
        ax.set_title(labels[family], fontsize=8, fontweight="bold")
        ax.set_xlabel(f"τ={sample.config.transmission:.2f}  σ={sample.config.blur_sigma:.2f}\nseed {sample.seed}", fontsize=6.5)
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_color("#CED4DA")
            spine.set_linewidth(0.6)
    fig.suptitle("Held-out compositions generated by the controlled image-formation model", fontsize=9.5, fontweight="bold", y=1.03)
    fig.tight_layout(w_pad=0.4)
    fig.savefig(ROOT / "figures" / "fig_sensor_shift_gallery.pdf", bbox_inches="tight")
    fig.savefig(ROOT / "figures" / "fig_sensor_shift_gallery.png", dpi=300, bbox_inches="tight")
    plt.close(fig)


if __name__ == "__main__":
    main()
